name = "duanwangzhi-qrcode-hub"
main = "index.js"
compatibility_date = "2025-03-10"

# 关键修改：移除所有 build 相关配置
# 因为 Wrangler 4.x 默认使用 ES 模块格式
# 不再需要显式声明 format

[[d1_databases]]
binding = "DB"
database_name = "duanwanghzi_kv"
database_id = "d33789fa-3981-4924-bc21-177442a556bb"

[triggers]
crons = ["0 2 */1 * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "qrcode_hub_dev"
database_id = "1cfa1ef6-a076-410b-aa19-50f63411313c"

[env.dev.triggers]
crons = ["*/10 * * * * *"]

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true
